version: "3"
services:
  db:
    container_name: auth # Here, container name means your DB name
    image: postgres:13
    volumes:
      - auth:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=mbr-sagor
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=auth
    ports:
      - 5433:5432
  container_name: djangoJWT
  build: ./app
  command: >
    sh -c "python manage.py collectstatic --noinput &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
  volumes:
    :/app/
  ports:
    - 8000:8000
  depends_on:
    - db
volumes:
  auth:
    driver: local
