version: "3"

services:
  db:
    container_name: auth
    image: postgres:12.5
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  server:
    container_name: django_jwt
    build: .
    restart: always
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db

volumes:
  media_data:
  static_data:
  postgres_data:
